### PR TITLE
fix column names in get_mids

### PR DESCRIPTION
**Pull request by cmdoret**
When running coolpup using a 2D bed file, I was getting the following error:

```
Traceback (most recent call last):
  File "/pasteur/scratch/users/cmatthey/softwares/anaconda3/bin/coolpup.py", line 10, in <module>
    sys.exit(main())
  File "/pasteur/scratch/users/cmatthey/softwares/anaconda3/lib/python3.7/site-packages/coolpuppy/__main__.py", line 237, in main
    mids = get_mids(bases, resolution=c.binsize, combinations=combinations)
  File "/pasteur/scratch/users/cmatthey/softwares/anaconda3/lib/python3.7/site-packages/coolpuppy/coolpup.py", line 63, in get_mids
    'Bin1', 'Bin2']).drop(['Bin1',
  File "/pasteur/scratch/users/cmatthey/softwares/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 4331, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/pasteur/scratch/users/cmatthey/softwares/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 4381, in duplicated
    raise KeyError(diff)
KeyError: Index(['chr'], dtype='object')
```

When looking at get_mids, I found that the 'chr' column was not supposed to be present and that there was a mistake  at line 64 where spaces were inserted in the column name. 

After correcting this, the program worked fine. Thanks for the nice and convenient software  :)

### CODE REVIEW

**Comment by Phlya** [comment]
Hi, thank you so much for bringing this to my attention, not sure how this creeped in!
Two comments: instead of changing the import to
`from coolpuppy import *`
Just fix it as a relative import:
from .plotpup import *

And for the main fix here: please rather fix it this way:
```
                            ).drop_duplicates(['chr1', 'chr2',
                                'Bin1', 'Bin2']).drop(['Bin1', 'Bin2'], axis=1)
```

We only want to drop duplicates of coordinates by chromosome. Thank you!

**Comment by Phlya** [comment]
OK, I actually have just pushed this myself with. Thank you again for spotting this!

**Comment by cmdoret** [comment]
Perfect, thanks for the update I rebased using your changes and it solved the issue. I also added a one-line change in a second commit to fix a bug happening with --save_all (see 7dc8962c0e75399acde8479cb2edcb7de185eda5). It's not pretty but it works ;)

**Comment by Phlya** [comment]
I see, thanks! Again, better to just move `prepare_single` to coolpup.py instead of __main__.py, and actually remove its second argument (together with all the commented lines), it's not needed anymore. If you'd like to do it, I'll happily merge your PR.

**Comment by cmdoret** [comment]
Done ! And it seems to work :+1:

**Comment by Phlya** [comment]
Great, thank you!

**Pull request merged**
